services:
  - type: web
    name: agrismart-app
    env: node
    plan: free
    buildCommand: npm install && cd src/client && npm install && npx vite build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    healthCheckPath: /
